using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Data;
using System.Web;
using System.Web.Mvc;

// This code was generated by C1 Scaffolder.

namespace MvcCodeFlowClientManual.Controllers
{
    public class FlexGridController : Controller
    {

        public ActionResult Index()
        {

            return View();
        }


    }
}